

Resources:

  APIGRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "inline-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - s3:*
                Resource: "*"

  APIGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: MyS3
      Body:
        swagger: '2.0'
        info:
          version: '2016-10-13T23:04:43Z'
          title: MyS3
        basePath: "/S3"
        schemes:
        - https
        paths:
          "/":
            get:
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  schema:
                    "$ref": "#/definitions/Empty"
                  headers:
                    Content-Length:
                      type: string
                    Timestamp:
                      type: string
                    Content-Type:
                      type: string
                '400':
                  description: 400 response
                '500':
                  description: 500 response
              security:
              - sigv4: []
              x-amazon-apigateway-integration:
                credentials: !GetAtt   APIGRole.Arn
                responses:
                  4\d{2}:
                    statusCode: '400'
                  default:
                    statusCode: '200'
                    responseParameters:
                      method.response.header.Content-Type: integration.response.header.Content-Type
                      method.response.header.Content-Length: integration.response.header.Content-Length
                      method.response.header.Timestamp: integration.response.header.Date
                  5\d{2}:
                    statusCode: '500'
                uri: arn:aws:apigateway:ap-southeast-2:s3:path//
                passthroughBehavior: when_no_match
                httpMethod: GET
                type: aws
